name: CI Build & Deploy

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ensure yarn is installed
        run: npm i -g yarn
      - name: Install deps
        run: yarn
      - name: Build & bundle
        run: yarn ui:build
  deploy:
    runs-on: ubuntu-latest
    name: A job to deploy the app to Fleek
    steps:
      - uses: actions/checkout@v3
      - name: Deploy site
        id: deploy
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
          workDir: 'dist'
      - name: Get the deploy url
        run: echo "Deploy url is ${{ steps.deploy.outputs.deployUrl }}"
